### ISSUE TITLE
Implement ODP Meeting Attendance Tracking for Alloy Meetings

### ISSUE THREAD

**Issue by brooklynrob** [finos/alloy#164]
- [x] Make sure that all Alloy meeting attendees are registered in metadata, with a github username set (preferably also with a corporate email, but not mandatory) - @aitana16 , can you help with this task?
- [x] Add [meetings.yml](https://github.com/finos/alloy/blob/master/.github/workflows/meetings.yml) action into github.com/finos/alloy - @maoo 
- [x] Add GitHub Issue template called `Alloy Meeting Minutes`, see https://github.com/finos/alloy/blob/master/.github/ISSUE_TEMPLATE/Meeting.md
- [x] Add GitHub Issues labels to specify which WG is meeting - @brooklynrob , can you help with this task?
- [x] Add meeting attendance tracking item into next Alloy WG meeting agenda - link to https://odp.finos.org/docs/project-collaboration/#meeting-minutes
- [x] Presenting meeting attendance tracking at next Alloy meeting

**Comment by maoo** [comment]
@aitana16, @brooklynrob - I've tested meeting tracking attendance on https://github.com/finos/alloy/issues/165 . We're all set.

Which is the next meeting you'd propose to present this?

**Comment by aitana16** [comment]
Hi @brooklynrob all regular Alloy pilot participants except for Yeonje Jo (Bloomberg) are registered in metadata with their GitHub IDs (see full list at https://docs.google.com/spreadsheets/d/1Egpd7xdaLE45xDvtp5T26ycrEHf38coSiiU2ONB8cWs/edit#gid=731728114)

**Comment by maoo** [comment]
I think we're done with this, closing issue.
