### ISSUE TITLE
Define GitHub Actions for building and testing Docker images

### ISSUE THREAD

**Issue by maoo** [finos/alloy#93]
Tasks
- [x] Create GitHub Action for MVN build
- [x] Automatic snapshot deployment on oss.sonatype.org (via GitHub Actions)
- [x] SonarCloud integration -> https://sonarcloud.io/code?id=org.finos.alloy%3Aalloy-parent
- [x] Create simple Dockerfile
- [x] Dockerfile + push to hub.docker.com/u/finos
- [x] Dry run of a manual (signed) deployment into Maven Central
- [x] Release [finos-parent-pom](github.com/finos/finos-parent-pom) - version `2`
- [x] @gs-bracej - Follow steps 1 and 2 from https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530342/Continuous+Integration#ContinuousIntegration-Continuous(artifact)deploymentinJava
- [x] Review build strategy with @gs-bracej 
- [x] Run `mvn deploy` locally
- [x] Run release using `-DdryRun=true`
- [x] Plan ahead next steps (new issue)

**Comment by maoo** [comment]
Delivered most of the features, still working on the release process. See https://github.com/finos/alloy/tree/build/build-sample

**Comment by maoo** [comment]
Permissions requested for @gs-bracej to run releases in Sonatype OSS and Central - https://issues.sonatype.org/browse/OSSRH-58186

**Comment by maoo** [comment]
New issues:
- https://github.com/finos/alloy/issues/130
- https://github.com/finos/alloy/issues/131
